on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'yarn'

        - name: Install dependencies
          run: npm install --global yarn && yarn install --frozen-lockfile
        
        - name: "Setup npm"
          run: |
            npm set @dario13:registry=https://npm.pkg.github.com/dario13
            npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

        - name: "Create version and publish "
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor}}@users.noreply.github.com"
            git stash
            git checkout ${{ github.ref }}
            yarn lerna publish from-git --yes