name: ci
on:
  pull_request:
    types: [labeled]

jobs:
  pre-publish:
    name: Pre-publish
    if: github.event.label.name == 'ready-to-merge'
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'yarn'

        - name: Install dependencies
          run: npm install --global yarn && yarn install --frozen-lockfile

        - name: Run lint
          run: yarn lint

        - name: Format code
          run: yarn format

        - name: Run tests
          run: yarn test

        - name: Initialize CodeQL
          uses: github/codeql-action/init@v2
          with:
            languages: javascript

        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v2

